-- Autotest des contrôles E1 : schéma NON CONFORME, chaque écart étant volontaire.
-- Sert à prouver que verifier-socle.sh DÉTECTE chaque violation (un contrôle qui ne
-- peut pas échouer ne prouve rien). La correspondance écart → contrôle attendu est
-- tenue dans lancer-autotest.sh.

\set ON_ERROR_STOP 1
SET client_min_messages = warning;

DROP SCHEMA IF EXISTS recette_ko CASCADE;
CREATE SCHEMA recette_ko AUTHORIZATION qa_ged_owner;
GRANT USAGE ON SCHEMA recette_ko TO qa_ged_app, qa_ged_readonly;
GRANT CREATE ON SCHEMA recette_ko TO qa_ged_app;                 -- E1-C33, E1-P01
GRANT CREATE ON SCHEMA recette_ko TO PUBLIC;                     -- E1-C40

SET ROLE qa_ged_owner;
SET search_path = recette_ko;
-- Aucun ALTER DEFAULT PRIVILEGES                                 -- E1-C41

CREATE TABLE "TypeDocument" (                                    -- E1-C01
  id bigserial CONSTRAINT pk_type_document PRIMARY KEY,          -- E1-C05, E1-C06
  "nomComplet" text                                              -- E1-C02
);

CREATE TABLE noeud (
  id uuid CONSTRAINT pk_noeud PRIMARY KEY,
  nom text
);
INSERT INTO noeud VALUES (gen_random_uuid(), 'espace amorcé par changeset'); -- E1-C23

CREATE TABLE document (
  id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_document PRIMARY KEY, -- E1-C05, E1-C06
  noeud uuid CONSTRAINT document_noeud_fkey REFERENCES noeud (id), -- E1-C07, E1-C08, E1-C13
  nom text CONSTRAINT document_nom_key UNIQUE                      -- E1-C09
           CONSTRAINT document_nom_check CHECK (nom <> ''),        -- E1-C10
  metadonnees text,                                                -- E1-C17, E1-C18
  cree_le timestamp,                                               -- E1-C14
  supprime boolean                                                 -- E1-C15, E1-C16
);
CREATE INDEX document_cree_le_ix ON document (cree_le);          -- E1-C11
CREATE INDEX idx_autre_nom ON document (nom);                    -- E1-C12

CREATE TABLE lien (a uuid, b uuid);                              -- E1-C03
CREATE TABLE role_permission (                                   -- E1-C04
  role_id uuid, permission_id uuid,
  CONSTRAINT pk_role_permission PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE journal_audit (id uuid CONSTRAINT pk_journal_audit PRIMARY KEY, action text);

CREATE TABLE flyway_schema_history (id uuid CONSTRAINT pk_flyway_schema_history PRIMARY KEY); -- E1-C19
CREATE TABLE databasechangelog (
  id varchar(255) NOT NULL, author varchar(255) NOT NULL, filename varchar(255) NOT NULL,
  dateexecuted timestamp NOT NULL, orderexecuted integer NOT NULL, exectype varchar(10) NOT NULL,
  md5sum varchar(35), description varchar(255), comments varchar(255), tag varchar(255),
  liquibase varchar(20), contexts varchar(255), labels varchar(255), deployment_id varchar(10)
);
INSERT INTO databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype) VALUES
  ('1', 'dev', 'db/migration/V1__init.sql', now(), 1, 'EXECUTED'),        -- E1-C20, E1-C22
  ('2', 'dev', 'db/changelog/202610011200_Table.xml', now(), 2, 'FAILED'); -- E1-C20, E1-C21

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA recette_ko TO qa_ged_app;
REVOKE DELETE ON lien FROM qa_ged_app;                           -- E1-C34
GRANT TRIGGER ON lien TO qa_ged_app;                             -- E1-C35
GRANT SELECT ON ALL TABLES IN SCHEMA recette_ko TO qa_ged_readonly;
REVOKE SELECT ON role_permission FROM qa_ged_readonly;           -- E1-C39
GRANT INSERT ON document TO qa_ged_readonly;                     -- E1-C38, E1-P09
-- journal_audit : ged_app garde UPDATE et DELETE                -- E1-C36, E1-P21, E1-P22
GRANT SELECT ON document TO PUBLIC;                              -- E1-C40

RESET ROLE;
-- Objet créé hors ged_owner                                      -- E1-C32
CREATE TABLE recette_ko.objet_orphelin (id uuid CONSTRAINT pk_objet_orphelin PRIMARY KEY);
GRANT SELECT, INSERT, UPDATE, DELETE ON recette_ko.objet_orphelin TO qa_ged_app;
GRANT SELECT ON recette_ko.objet_orphelin TO qa_ged_readonly;
RESET search_path;
